export const Videos = [
  { label: "Video 1", id: "1" },
  { label: "Video 2", id: "2" },
  { label: "Video 3", id: "3" },
  { label: "Video 4", id: "4" },
  { label: "Video 5", id: "5" },
  { label: "Video 6", id: "6" },
  { label: "Video 7", id: "7" },
  { label: "Video 8", id: "8" },
  { label: "Video 9", id: "9" },
  { label: "Video 10", id: "10" },
  { label: "Video 11", id: "11" },
  { label: "Video 12", id: "12" },
  { label: "Video 13", id: "13" },
  { label: "Video 14", id: "14" },
  { label: "Video 15", id: "15" },
  { label: "Video 16", id: "16" },
  { label: "Video 17", id: "17" },
  { label: "Video 18", id: "18" },
  { label: "Video 19", id: "19" },
  { label: "Video 20", id: "20" },
  { label: "Video 21", id: "21" },
  { label: "Video 22", id: "22" },
  { label: "Video 23", id: "23" },
  { label: "Video 24", id: "24" },
  { label: "Video 25", id: "25" },
];
